# Generated by Django 5.2.6 on 2026-01-02 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0014_alter_contrato_options_alter_pago_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudNotaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('SolicitudCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_admin', to='inmobiliaria.solicitudcliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
