# Generated by Django 5.2.6 on 2026-01-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0015_solicitudnotaadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudnotaadmin',
            old_name='SolicitudCliente',
            new_name='Solicitud',
        ),
    ]
