# Generated by Django 5.2.6 on 2026-01-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0016_rename_solicitudcliente_solicitudnotaadmin_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudnotaadmin',
            old_name='Solicitud',
            new_name='solicitud',
        ),
    ]
