# Generated by Django 5.2.6 on 2026-01-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0017_rename_solicitud_solicitudnotaadmin_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
