# Generated by Django 5.2.6 on 2026-01-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0019_backfill_propiedad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
