# Generated by Django 5.2.6 on 2026-01-07 20:05

import django.db.models.deletion
import inmobiliaria.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0020_alter_propiedad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', validators=[inmobiliaria.validators.validar_pdf], verbose_name='Archivo PDF del contrato'),
        ),
        migrations.CreateModel(
            name='ContratoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato firmado'), ('acreditacion', 'Acreditación'), ('herencia', 'Herencia / posesión efectiva'), ('certificado', 'Certificado'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('archivo', models.FileField(upload_to='contratos/documentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inmobiliaria.contrato')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
