# Generated by Django 5.2.6 on 2026-01-08 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0021_alter_contrato_archivo_pdf_contratodocumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedaddocumento',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='propiedaddocumento',
            old_name='subido',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='contrato',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedaddocumento',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedaddocumento',
            name='tipo',
            field=models.CharField(choices=[('acreditacion', 'Acreditación / dominio'), ('herencia', 'Herencia / posesión efectiva'), ('certificado', 'Certificado'), ('avaluo', 'Tasación / avalúo'), ('plano', 'Plano / croquis'), ('identidad', 'Identidad propietario'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
        migrations.AlterField(
            model_name='propiedaddocumento',
            name='archivo',
            field=models.FileField(upload_to='propiedades/documentos/'),
        ),
        migrations.AlterField(
            model_name='propiedaddocumento',
            name='nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
