# Generated by Django 5.2.6 on 2026-01-09 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0022_alter_propiedaddocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotacontrato',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cuotacontrato',
            name='inmobiliari_vencimi_3abbb9_idx',
        ),
        migrations.AlterField(
            model_name='cuotacontrato',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuotacontrato',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.pago'),
        ),
    ]
