# Generated by Django 5.2.6 on 2026-01-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0023_alter_cuotacontrato_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cuotacontrato',
            constraint=models.UniqueConstraint(fields=('contrato', 'vencimiento'), name='uniq_cuota_contrato_vencimiento'),
        ),
    ]
