# Generated by Django 5.2.6 on 2026-01-10 12:25

import inmobiliaria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0024_cuotacontrato_uniq_cuota_contrato_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesado',
            name='rut',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[inmobiliaria.validators.validar_rut]),
        ),
    ]
