# Generated by Django 5.2.6 on 2026-01-11 02:24

import inmobiliaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0026_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotacontrato',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to=inmobiliaria.models.upload_comprobante_cuota),
        ),
    ]
